{% set name = "pytest-shard" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-shard-{{ version }}.tar.gz
  sha256: b86a967fbfd1c8e50295095ccda031b7e890862ee06531d5142844f4c1d1cd67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest

test:
  imports:
    - pytest_shard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AdamGleave/pytest-shard
  dev_url: https://github.com/AdamGleave/pytest-shard
  license: MIT
  license_file: LICENSE.txt
  description: Shards tests based on a hash of their test name enabling easy parallelism across machines, suitable for a wide variety of continuous integration services. Tests are split at the finest level of granularity, individual test cases, enabling parallelism even if all of your tests are in a single file (or even single parameterized test method).
  summary: Shards tests based on a hash of their test name.

extra:
  recipe-maintainers:
    - baszalmstra
